apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-test-pvc
  labels:
    app: vsphere-test
spec:
  storageClassName: vsphere-tkg-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
