apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: 
  namespace: 
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: 
    controlPlane:
      replicas: 
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=
    variables:
      - name: vmClass
        value: 
      - name: storageClass
        value: 
      - name: defaultStorageClass
        value: 
