apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmbeans-deployment
spec:
  selector:
    matchLabels:
      app: vmbeans
  replicas: 1
  template:
    metadata:
      labels:
        app: vmbeans
    spec:
      containers:
        - name: vmbeans
          image: projects.registry.vmware.com/vclass/vmbeans-website:v1.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vmbeans-service
  labels:
    app: vmbeans
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vmbeans
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vmbeans-httpproxy
spec:
  virtualhost:
    fqdn: vmbeans-contour.tkg.vclass.local
  routes:
    - services:
      - name: vmbeans-service
        port: 80
