kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-user-developer_01
  namespace: 
roleRef:
  kind: ClusterRole
  name: edit                            
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: 
  name:             #sso:<username>@<domain>
  apiGroup: rbac.authorization.k8s.io
