kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-user-developer_01
  namespace: dev-namespace
roleRef:
  kind: ClusterRole
  name: edit                            
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:developer_01@vsphere.local
  apiGroup: rbac.authorization.k8s.io
