namespace: tanzu-system-service-discovery
deployment:
  args:
    - --source=service
    - --source=ingress
    - --domain-filter=tkg.vclass.local
    - --policy=upsert-only
    - --registry=txt
    - --txt-owner-id=k8s
    - --txt-prefix=external-dns-
    - --provider=rfc2136
    - --rfc2136-host=172.20.10.10
    - --rfc2136-port=53
    - --rfc2136-zone=vclass.local
    - --rfc2136-tsig-secret=Ss4Qs5Dy+rFi16Wuv6sBdVo/ATAihgl1SalpnKxh4ow=
    - --rfc2136-tsig-secret-alg=hmac-sha256
    - --rfc2136-tsig-keyname=externaldns-key2
    - --rfc2136-tsig-axfr
  env: []
  securityContext: {}
  volumeMounts: []
  volumes: []
